src = ["../src", "../tests"]
line-length = 120
include = ["../src/**/*.py", "../tests/**/*.py"]


[lint]
ignore = [
    "PTH123",  # replacing open with Path.open is not really idiomatic
]
extend-select = [
    "I",   # isort
    "PTH", # path
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]

[lint.pydocstyle]
convention = "google"
